services:
  backend-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - "./bots:/backend-api/bots"
      - /var/run/docker.sock:/var/run/docker.sock
      - "./certs:/backend-api/certs:ro"
      - "./conf:/backend-api/conf"
    env_file:
      - .env
    environment:
      - BROKER_HOST=emqx
      - BROKER_PORT=1883
      - BOTS_PATH=/backend-api/bots
      - GATEWAY_CERT_PATH=/backend-api/certs/server_cert.pem
      - GATEWAY_CERT_PASSPHRASE=${GATEWAY_CERT_PASSPHRASE}
      - DEFAULT_GATEWAY_CERTS_PATH=/backend-api/certs
      - CONFIG_PASSWORD=${CONFIG_PASSWORD}
      - CLIENT_CONFIG_PATH=/backend-api/conf/conf_client.yml
      - PYTHONPATH=/backend-api:$PYTHONPATH
      # Add these new environment variables for Hummingbot instances
      - GATEWAY_HOST=gateway
      - GATEWAY_PORT=15888
      - GATEWAY_CERTS_PATH=/certs
      - HUMMINGBOT_INSTANCE_TYPE=docker
    networks:
      - emqx-bridge
      - gateway-network

  gateway:
    image: mlguys/gateway:mango
    ports:
      - "15888:15888"
    volumes:
      - "./certs:/home/gateway/certs:ro"
    environment:
      - GATEWAY_CERT=/home/gateway/certs/server_cert.pem
      - GATEWAY_KEY=/home/gateway/certs/server_key.pem
      - GATEWAY_PASSPHRASE=${GATEWAY_CERT_PASSPHRASE}
      - CERTS_PATH=/home/gateway/certs
    networks:
      - gateway-network

  emqx:
    container_name: hummingbot-broker
    image: emqx:5
    restart: unless-stopped
    environment:
      - EMQX_NAME=emqx
      - EMQX_HOST=node1.emqx.local
      - EMQX_CLUSTER__DISCOVERY_STRATEGY=static
      - EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.local]
      - EMQX_LOADED_PLUGINS="emqx_recon,emqx_retainer,emqx_management,emqx_dashboard"
    volumes:
      - emqx-data:/opt/emqx/data
      - emqx-log:/opt/emqx/log
      - emqx-etc:/opt/emqx/etc
    ports:
      - "1883:1883" # mqtt:tcp
      - "8883:8883" # mqtt:tcp:ssl
      - "8083:8083" # mqtt:ws
      - "8084:8084" # mqtt:ws:ssl
      - "8081:8081" # http:management
      - "18083:18083" # http:dashboard
      - "61613:61613" # web-stomp gateway
    networks:
      emqx-bridge:
        aliases:
          - node1.emqx.local
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx_ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5

networks:
  emqx-bridge:
    driver: bridge
  gateway-network:
    driver: bridge

volumes:
  emqx-data: {}
  emqx-log: {}
  emqx-etc: {}
