services:
  backend-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/backend-api  # Mount the entire project directory
    environment:
      - ENABLE_DEBUGGER=true
      - PYTHONPATH=/backend-api
    ports:
      - "8000:8000"
      - "5678:5678"  # Debug port